#' Volcano Plot
#'
#' Plot a volcano plot for differential expression analysis.
#'
#' @param devil.res A data frame or tibble containing the results of differential expression analysis. This object is generated by the `test_de` function.
#' @param lfc_cut A numeric value specifying the threshold for absolute log-fold change. Genes with absolute log-fold change greater than or equal to this value are highlighted. (default is `1`)
#' @param pval_cut A numeric value specifying the threshold for adjusted p-value. Genes with adjusted p-value less than or equal to this value are highlighted. (default is `0.05`)
#' @param labels Logical indicating whether to label significant genes on the plot. (default is `TRUE`)
#' @param colors A character vector specifying the colors to use for different classes of genes (e.g., "non-significant", "lfc", "p-value", "p-value and lfc").
#'  Default colors are `"gray"`, `"forestgreen"`, `"steelblue"`, and `"indianred"`
#' @param color_alpha A numeric value specifying the alpha transparency level for point colors. (default is `0.7`)
#' @param point_size A numeric value specifying the size of points in the plot. (default is `1`)
#' @param center Logical indicating whether to center the x-axis at zero. (default is `TRUE`)
#' @param title A character string specifying the title of the plot. (default is `Volcano plot`)
#'
#' @return A `ggplot` object representing the volcano plot.
#'
#' @details This function creates a volcano plot for visualizing the results of differential expression analysis. It highlights genes based on their log-fold change (`lfc`) and adjusted p-values (`adj_pval`). Genes that meet the specified thresholds for both log-fold change and adjusted p-value are optionally labeled on the plot.
#'
#' The function also ensures that genes with an adjusted p-value of zero are displayed with a minimal p-value (`1e-16`) to avoid plotting issues.
#'
#' @export
plot_volcano <- function(
    devil.res,
    lfc_cut=1,
    pval_cut=.05,
    labels=TRUE,
    colors=c("gray", "forestgreen", "steelblue", "indianred"),
    color_alpha=.7,
    point_size=1,
    center=TRUE,
    title="Volcano plot") {

  if (sum(is.na(devil.res))) {
    message('Warning: some of the reults are unrealiable (i.e. contains NaN)\n Those genes will not be displayed')
    devil.res <- stats::na.omit(devil.res)
  }

  d <- devil.res %>%
    dplyr::mutate(pval_filter = .data$adj_pval <= pval_cut, lfc_filter = abs(.data$lfc) >= lfc_cut) %>%
    dplyr::mutate(class = dplyr::if_else(.data$pval_filter & .data$lfc_filter, "p-value and lfc",
                                        dplyr::if_else(.data$pval_filter, "p-value",
                                                      dplyr::if_else(.data$lfc_filter, "lfc", "non-significant")))) %>%
    dplyr::mutate(class = factor(class, levels = c("non-significant", "lfc", 'p-value', 'p-value and lfc'))) %>%
    dplyr::mutate(label = dplyr::if_else(class == 'p-value and lfc', .data$name, NA))


  if (sum(d$adj_pval == 0) > 0) {
    message(paste0(sum(d$adj_pval == 0), ' genes have adjusted p-value equal to 0, will be set to 1e-16'))
    d$adj_pval[d$adj_pval == 0] <- 1e-16
  }

  p <- d %>%
    ggplot2::ggplot(mapping = ggplot2::aes(x=.data$lfc, y=-log10(.data$adj_pval), col=.data$class, label=.data$label)) +
    ggplot2::geom_point(alpha = color_alpha, size=point_size) +
    ggplot2::theme_minimal() +
    ggplot2::labs(x = expression(Log[2] ~ FC), y = expression(-log[10] ~ Pvalue), col="") +
    ggplot2::scale_color_manual(values = colors) +
    ggplot2::geom_vline(xintercept = c(-lfc_cut, lfc_cut), linetype = 'dashed') +
    ggplot2::geom_hline(yintercept = -log10(pval_cut), linetype = "dashed") +
    ggplot2::ggtitle(title) +
    ggplot2::theme(legend.position = 'bottom')

  if (center) { p <- p + ggplot2::xlim(c(-max(abs(d$lfc)), max(abs(d$lfc))))}
  if (labels) { p <- p + ggplot2::geom_text(col = 'black', check_overlap = TRUE, na.rm = TRUE)}
  p
}
