# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

init_beta <- function(y, X) {
    .Call('_devil_init_beta', PACKAGE = 'devil', y, X)
}

beta_fit <- function(y, X, mu_beta, off, k, max_iter, eps) {
    .Call('_devil_beta_fit', PACKAGE = 'devil', y, X, mu_beta, off, k, max_iter, eps)
}

beta_fit_group <- function(y, mu_beta, off, k, max_iter, eps) {
    .Call('_devil_beta_fit_group', PACKAGE = 'devil', y, mu_beta, off, k, max_iter, eps)
}

lte_n_equal_rows <- function(matrix, n, tolerance = 1e-10) {
    .Call('_devil_lte_n_equal_rows', PACKAGE = 'devil', matrix, n, tolerance)
}

get_row_groups <- function(matrix, n_groups, tolerance = 1e-10) {
    .Call('_devil_get_row_groups', PACKAGE = 'devil', matrix, n_groups, tolerance)
}

initialize_beta_univariate_matrix_cpp <- function(X, Y, sf) {
    .Call('_devil_initialize_beta_univariate_matrix_cpp', PACKAGE = 'devil', X, Y, sf)
}

preprocess_data <- function(y, X, off) {
    .Call('_devil_preprocess_data', PACKAGE = 'devil', y, X, off)
}

beta_fit_efficient <- function(y_sums, counts, X, mu_beta, off, k, max_iter, eps) {
    .Call('_devil_beta_fit_efficient', PACKAGE = 'devil', y_sums, counts, X, mu_beta, off, k, max_iter, eps)
}

estimate_mom_dispersion_efficient <- function(y_sums_vec, y_sq_sums_vec, X_unique, sf_unique, counts, beta_g, N_total) {
    .Call('_devil_estimate_mom_dispersion_efficient', PACKAGE = 'devil', y_sums_vec, y_sq_sums_vec, X_unique, sf_unique, counts, beta_g, N_total)
}

compute_hessian_efficient <- function(beta, overdispersion, y_sums, counts, X_unique, sf_unique) {
    .Call('_devil_compute_hessian_efficient', PACKAGE = 'devil', beta, overdispersion, y_sums, counts, X_unique, sf_unique)
}

compute_scores_efficient <- function(X_unique, y_sums, counts, beta, overdispersion, sf_unique) {
    .Call('_devil_compute_scores_efficient', PACKAGE = 'devil', X_unique, y_sums, counts, beta, overdispersion, sf_unique)
}

compute_clustered_meat_efficient <- function(X_unique, y_sums_per_group_cluster, counts_per_group_cluster, group_to_cluster_map, beta, overdispersion, sf_unique_per_pair, num_clusters, N_total) {
    .Call('_devil_compute_clustered_meat_efficient', PACKAGE = 'devil', X_unique, y_sums_per_group_cluster, counts_per_group_cluster, group_to_cluster_map, beta, overdispersion, sf_unique_per_pair, num_clusters, N_total)
}

aggregate_vector_by_group_efficient <- function(y, mapping, n_groups) {
    .Call('_devil_aggregate_vector_by_group_efficient', PACKAGE = 'devil', y, mapping, n_groups)
}

estimate_mom_dispersion_cpp <- function(count_matrix, design_matrix, beta_matrix, sf) {
    .Call('_devil_estimate_mom_dispersion_cpp', PACKAGE = 'devil', count_matrix, design_matrix, beta_matrix, sf)
}

H_log_gh_cpp <- function(p, s, t, gh_order = 32L, max_newton = 8L, newton_tol = 1e-12) {
    .Call('_devil_H_log_gh_cpp', PACKAGE = 'devil', p, s, t, gh_order, max_newton, newton_tol)
}

H_log_gh_pmhalf <- function(s, t, gh_order = 32L, max_newton = 8L, newton_tol = 1e-12) {
    .Call('_devil_H_log_gh_pmhalf', PACKAGE = 'devil', s, t, gh_order, max_newton, newton_tol)
}

fit_overdispersion_cppp <- function(y, X, mu_beta, off, kappa, max_iter, eps_theta, newton_max = 16L, y_unique_cap = 4096L) {
    .Call('_devil_fit_overdispersion_cppp', PACKAGE = 'devil', y, X, mu_beta, off, kappa, max_iter, eps_theta, newton_max, y_unique_cap)
}

make_table_if_small <- function(x, stop_if_larger) {
    .Call('_devil_make_table_if_small', PACKAGE = 'devil', x, stop_if_larger)
}

conventional_loglikelihood_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call('_devil_conventional_loglikelihood_fast', PACKAGE = 'devil', y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

conventional_score_function_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call('_devil_conventional_score_function_fast', PACKAGE = 'devil', y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

conventional_deriv_score_function_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call('_devil_conventional_deriv_score_function_fast', PACKAGE = 'devil', y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

compute_hessian <- function(beta, overdispersion, y, design_matrix, size_factors) {
    .Call('_devil_compute_hessian', PACKAGE = 'devil', beta, overdispersion, y, design_matrix, size_factors)
}

compute_scores <- function(design_matrix, y, beta, overdispersion, size_factors) {
    .Call('_devil_compute_scores', PACKAGE = 'devil', design_matrix, y, beta, overdispersion, size_factors)
}

compute_clustered_meat <- function(design_matrix, y, beta, overdispersion, size_factors, clusters) {
    .Call('_devil_compute_clustered_meat', PACKAGE = 'devil', design_matrix, y, beta, overdispersion, size_factors, clusters)
}

compute_meat <- function(design_matrix, y, beta, overdispersion, size_factors) {
    .Call('_devil_compute_meat', PACKAGE = 'devil', design_matrix, y, beta, overdispersion, size_factors)
}

compute_clustered_meat_fast <- function(design_matrix, y, beta, overdispersion, size_factors, cluster_blocks_indexes) {
    .Call('_devil_compute_clustered_meat_fast', PACKAGE = 'devil', design_matrix, y, beta, overdispersion, size_factors, cluster_blocks_indexes)
}

